services:
  api:
    container_name: vkteams_api
    build:
      context: ./api/.
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Moscow
    env_file:
      - api/config/.env
    command: fastapi run
    volumes:
      - ./db:/db
    networks:
      - project_network
    ports:
      - 8003:8000
    user: "1000:1000"
    restart: on-failure

networks:
  project_network:
    driver: bridge