services:
  api:
    container_name: api
    build:
      context: ./api/.
      dockerfile: Dockerfile
    env_file:
      - api/config/.env
    command: fastapi run
    volumes:
      - db-vkteams:/db
    networks:
      - project_network
    ports:
      - 8003:8000

volumes:
  db-vkteams:
    driver_opts:
      type: none
      device: ./db
      o: bind

networks:
  project_network:
    driver: bridge