services:
  api:
    container_name: api
    build:
      context: ./api/.
      dockerfile: Dockerfile
    env_file:
      - api/config/.env
    command: fastapi run
    volumes:
      - ./db:/db
    networks:
      - project_network
    ports:
      - 8003:8000
    user: "1000:1000"

networks:
  project_network:
    driver: bridge